# Generated by Django 5.0.1 on 2024-01-24 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('matricula', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('nome_completo', models.CharField(max_length=250)),
                ('primeiro_nome', models.CharField(max_length=50)),
                ('ultimo_nome', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('campus', models.CharField(max_length=4)),
                ('curso', models.CharField(max_length=75)),
                ('email_pessoal', models.EmailField(max_length=250, unique=True)),
                ('email_escolar', models.EmailField(max_length=250, unique=True)),
                ('email_academico', models.EmailField(max_length=250, unique=True)),
                ('sexo', models.CharField(max_length=1)),
                ('tipo_vinculo', models.CharField(max_length=20)),
                ('data_nascimento', models.DateField()),
                ('url_foto', models.URLField(max_length=500)),
            ],
        ),
    ]
